# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipeline.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pipeline.proto',
  package='protogen',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0epipeline.proto\x12\x08protogen2\x11\n\x0fPipelineServiceb\x06proto3')
)



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PIPELINESERVICE = _descriptor.ServiceDescriptor(
  name='PipelineService',
  full_name='protogen.PipelineService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=28,
  serialized_end=45,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_PIPELINESERVICE)

DESCRIPTOR.services_by_name['PipelineService'] = _PIPELINESERVICE

# @@protoc_insertion_point(module_scope)
